apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-nfs-pvc-dynamic
  namespace: nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: demo-nfs-storage